### PR TITLE
Update scripts

### PR DESCRIPTION
**Pull request by bourdakos1**
This PR:
- removes the unused makefile
- adds a `watch` script to the package.json
- converts `create-release.py` to typescript 
- adds a build step to the release script (`create-release.py` doesn't publish a valid package)
- updates the help description to match the actual functionality
- adds a `--dry-run` flag to test run without doing anything destructive
 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Comment by lresende** [comment]
What was wrong with create-release.py?

**Comment by bourdakos1** [comment]
It was the only piece of code that used python. To run it, you need to have python installed, set up an env, and figure out what dependencies need to be installed (semantic_version needed to be pip installed). Additionally, linting and formatting is set up for typescript, but we don’t have anything similar set up for python (and feels like overkill to set  up for one script). I would be a bit more okay to keep create_release.py if it worked out-of-the-box, but still would prefer to keep this project one language.

**Comment by bourdakos1** [comment]
@lresende I broke up the `release` script into `version`, `changelog` and `publish` scripts. WIth the intention of running `version` + `changelog` and then creating a PR to be reviewed. Once approved/merged we would run the `publish` command which would tag a release and publish the packages. We could either run `publish` manually or set up ci to handle publishing

**Comment by lresende** [comment]
Outdated

**Pull request closed without merging**
