### PR TITLE
Update initial empty pipeline json to be valid

### LINKED ISSUE #2066: Invalid pipeline files are produced prior to save
When opening a new pipeline in the Visual Pipeline Editor (VPE), a file is immediately produced reflecting the empty canvas.  If the user then closes the editor, that file remains but is actually different (and invalid) from a pipeline produced if the user simply hits 'save' from an empty canvas.  In that case, a _valid_ empty pipeline file is produced.

The VPE should produce a valid empty pipeline file during this initial period or ensure the file's removal if the VPE is closed and the user has not saved the pipeline themselves.  If there is checkpointing happening, then the first option (always persist a valid pipeline) is probably preferred.

**Steps to reproduce the behavior:**
1. Create a new pipeline
2. Exit the pipeline editor without saving the pipeline

The following is produced (filename, in this case, is `untitled.pipeline`:
```JSON
{
  "doc_type": "pipeline",
  "version": "3.0",
  "json_schema": "http://api.dataplatform.ibm.com/schemas/common-pipeline/pipeline-flow/pipeline-flow-v3-schema.json",
  "id": "elyra-auto-generated-pipeline",
  "primary_pipeline": "primary",
  "pipelines": [
    {
      "id": "primary",
      "nodes": [],
      "app_data": {
        "ui_data": {
          "comments": []
        },
        "version": 4,
        "runtime": "kfp"
      },
      "runtime_ref": ""
    }
  ],
  "schemas": []
}
```
Next, save that same pipeline and get the following (in the same `untitled.pipeline` file):
```JSON
{
  "doc_type": "pipeline",
  "version": "3.0",
  "json_schema": "http://api.dataplatform.ibm.com/schemas/common-pipeline/pipeline-flow/pipeline-flow-v3-schema.json",
  "id": "elyra-auto-generated-pipeline",
  "primary_pipeline": "primary",
  "pipelines": [
    {
      "id": "primary",
      "nodes": [],
      "app_data": {
        "ui_data": {
          "comments": []
        },
        "version": 4,
        "runtime": "kfp",
        "properties": {
          "name": "untitled",
          "runtime": "Kubeflow Pipelines"
        }
      },
      "runtime_ref": ""
    }
  ],
  "schemas": []
}
```
Note the existence of the `properties` stanza.

**Expected behavior**
A valid pipeline should always be persisted - even when the persistence is implicit.

There are test resources reflecting "empty" pipelines that are of the _invalid_ form.  Those test resources (and potentially the corresponding tests) should be updated as well.

Note: It should probably be noted that the use of _invalid_ here may be too strict because, currently, the _invalid_ empty pipeline would pass validation, although it would be considered a _Generic_ pipeline when the user actually chose _Kubeflow_ (or _AIrflow_).  As a result, we may want to ensure a `properties` stanza exists when [validating the pipeline's structure](https://github.com/elyra-ai/elyra/blob/31c3816acbfe41737ef5a2f0627c90419175f0a6/elyra/pipeline/validate.py#L128).  This check should probably be sensitive to pipeline versions >= 4.

### PR DESCRIPTION
**Pull request by ajbozarth**
Currently it is missing the `app_data.properties` fields which
is normally added in an initial save. The contents are still added
at save, since that is a hook in Elyra, but `properties` is now set
to an empty dict initially.

Fixes https://github.com/elyra-ai/elyra/issues/2066

 
Developer's Certificate of Origin 1.1

       By making a contribution to this project, I certify that:

       (a) The contribution was created in whole or in part by me and I
           have the right to submit it under the Apache License 2.0; or

       (b) The contribution is based upon previous work that, to the best
           of my knowledge, is covered under an appropriate open source
           license and I have the right under that license to submit that
           work with modifications, whether created in whole or in part
           by me, under the same open source license (unless I am
           permitted to submit under a different license), as indicated
           in the file; or

       (c) The contribution was provided directly to me by some other
           person who certified (a), (b) or (c) and I have not modified
           it.

       (d) I understand and agree that this project and the contribution
           are public and that a record of the contribution (including all
           personal information I submit with it, including my sign-off) is
           maintained indefinitely and may be redistributed consistent with
           this project or the open source license(s) involved.

### CODE REVIEW

**Review by marthacryan — APPROVED** [review]
This change makes sense to me and LGTM - haven't tested locally though

**Comment by ptitzler** [comment]
Can't review due to https://github.com/elyra-ai/pipeline-editor/issues/158

**Comment by akchinSTC** [comment]
need to update instructions on how to build and test this PR

**Comment by ajbozarth** [comment]
@akchinSTC there's no special build steps for this, as for testing, as @ptitzler mentioned, there's no longer a specific test-case for this, it's just future-proofing

**Comment by lresende** [comment]
Don't we need to populate the pipeline type when the pipeline gets created? 
Here is a diff between an empty pipeline vs saved one.

image

**Comment by ajbozarth** [comment]
@lresende the reason we can't set the contents of properties here is because those are dynamically set in the save hook in elyra. As far as pipeline-editor is concerned there's no way to call that hook. If we want we could add another hook on elyra's side to call the save hook on open, but I felt that wasn't the best solution so instead I just did this

**Comment by ptitzler** [comment]
@ajbozarth Using 3.0.1/master these [empty pipeline files](https://github.com/elyra-ai/pipeline-editor/files/7088600/empty_pipelines.tar.gz) are produced if one performs the following steps:
- click [generic|kfp|aa] pipeline editor tile in launcher
- close pipeline VPE

Note that [primary-pipeline]`app_data.runtime` is set for airflow and kfp but not generic pipelines.

**Comment by lresende** [comment]
> Note that [primary-pipeline]`app_data.runtime` is set for airflow and kfp but not generic pipelines.

@ajbozarth is this is the case, can we make it consistent?

**Comment by ajbozarth** [comment]
We can do it if we want, but iirc we were intentionally not doing that (ie leaving it unset for generic). I can't remember the reason, but I do remember discussion about it and the decision.

**Comment by ptitzler** [comment]
Perhaps because legacy pipelines didn't set this property?

**Pull request merged**
